# Generated by Django 4.2.10 on 2024-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='element_symbol',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
