# Generated by Django 4.2.10 on 2024-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metals', '0004_alter_metal_element_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='element_symbol',
        ),
        migrations.AddField(
            model_name='metal',
            name='symbol',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
